name: Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@v4

      # decode keystore from base64 secret
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks

      # set env variables
      - name: Set env variables
        run: |
          echo "KEYSTORE_PATH=$(pwd)/app/keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{  secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_TESTERS=${{  secrets.FIREBASE_TESTERS }}" >> $GITHUB_ENV

      # setup jdk
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # build signed apk
      - name: Build Signed APK
        run: ./gradlew clean assembleRelease

      # setup ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      # install ruby dependencies
      - name: Install Ruby Dependencies
        run: bundle install --path vendor/bundle

      # decode firebase creds file from base64 secret
      - name: Decode Firebase Credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 -d > service-account.json

      # upload to firebase app distr. via fastlane
      - name: Fastlane
        run: bundle exec fastlane beta